In [14]:
import pandas as pd
#import json
from bs4 import BeautifulSoup
#import xml.etree.ElementTree as ET
import numpy as np
#xmlp = ET.XMLParser(encoding="utf-8")
mon = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

In [15]:
def opxml(year = 2015, month = "01"):
    fp = fr'C:\Users\T14 Gen 3\Documents\tibame-project\weatherData\mn_Report_{year}{month}.xml'
    with open(fp, encoding = "UTF-8") as we:
        qw = we.read()
    return BeautifulSoup(qw, "xml")

In [16]:
def stationN(qwe):
  staN = [np.nan for x in range(4)]
  staN[0] = qwe.find('StationID').text
  staN[1] = qwe.find('StationName').text
  staN[2] = qwe.find('StationNameEN').text
  staN[3] = qwe.find('StationAttribute').text
  # print(pd.DataFrame(staN))
  return staN

In [17]:
def maxcou():
    cou = []
    for j in range(2015, 2024):
        for k in mon:
            xdd = opxml(j, k)   
            for asd in xdd.find_all('StationID'):
                if(asd.text not in cou):
                    cou.append(asd.text)
    return len(cou)

In [18]:
def hea(ye = 2022, n = 0):
    zxc = [np.nan for x in range(19)]
    xdd = opxml(ye, mon[n])
    zxc[0] = "Year-Month"
    i = 1
    for asd in xdd.find_all('weatherElement'):
        asd = BeautifulSoup(str(asd), 'xml')
        temp = asd.find('tagName').text
        unit = f" ({asd.find('units').text})"
        for qwe in asd.find_all('methodTagName'):
            zxc[i] = f"{qwe.text} {temp}"
            if(("Date" not in qwe.text) and ("Day" not in qwe.text)):
                zxc[i] += unit
            i += 1
    return zxc

In [19]:
def ma():
    mm = maxcou()
    ww, hh, dd = 19, 109, mm
    zzxc = [[[np.nan for x in range(ww)] for y in range(hh)] for z in range(dd)]
    ye = 1
    count = 0
    for j in range(2015, 2024):
        for k in mon:
            xdd = opxml(j, k)
            i = count
            for asd in xdd.find_all('location'):
                asd = BeautifulSoup(str(asd), 'xml')
                qaz = asd.find('StationID').text
                #qaz = BeautifulSoup(str(qaz), 'xml')
                bo = 0
                for ll in range(mm):
                    l = zzxc[ll][0][0]
                    #l = BeautifulSoup(str(l), 'xml')
                    if(qaz == l):
                        i = ll
                        bo = 100
                        #print(l.text)
                        continue
                if(bo != 100):
                    i = count
                    zzxc[i][0] = stationN(asd)
                    count += 1
                zzxc[i][ye][0] = f"{str(j)}-{k}"
                for qwe in asd.find_all('AirTemperature'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][1] = qwe.find('Mean').text
                    zzxc[i][ye][2] = qwe.find('Maximum').text
                    zzxc[i][ye][3] = qwe.find('MaximumDate').text
                    zzxc[i][ye][4] = qwe.find('Minimum').text
                    zzxc[i][ye][5] = qwe.find('MinimumDate').text
                for qwe in asd.find_all('Precipitation'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][6] = qwe.find('Accumulation').text
                    zzxc[i][ye][7] = qwe.find('GE01Days').text
                for qwe in asd.find_all('WindSpeed'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][8] = qwe.find('Maximum').text
                    zzxc[i][ye][9] = qwe.find('MaximumDate').text
                for qwe in asd.find_all('WindDirection'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][10] = qwe.find('Maximum').text
                for qwe in asd.find_all('PeakGustSpeed'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][11] = qwe.find('Maximum').text
                    zzxc[i][ye][12] = qwe.find('MaximumDate').text
                for qwe in asd.find_all('PeakGustDirection'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][13] = qwe.find('Maximum').text
                for qwe in asd.find_all('RelativeHumidity'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][14] = qwe.find('Mean').text
                    zzxc[i][ye][15] = qwe.find('Minimum').text
                    zzxc[i][ye][16] = qwe.find('MinimumDate').text
                for qwe in asd.find_all('AirPressure'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][17] = qwe.find('Mean').text
                for qwe in asd.find_all('SunshineDuration'):
                    qwe = BeautifulSoup(str(qwe), 'xml')
                    zzxc[i][ye][18] = qwe.find('Total').text
            ye += 1
    return zzxc

In [20]:
def wea(i:int, zzxc = ma()):
    return zzxc[i][:][:]
    # pd.DataFrame(t00, columns = hea())

In [21]:
def nam():
    nam = [[np.nan for x in range(4)] for y in range(31)]
    for i in range(31):
        zzxc = wea(i)
        nam[i][0] = zzxc[0][0]
        nam[i][1] = zzxc[0][1]
        nam[i][2] = zzxc[0][2]
        nam[i][3] = zzxc[0][3]
    return nam

In [22]:
def datae():
    dt = [[np.nan for x in range(20)] for y in range(3061)]
    o = 0
    for i in range(maxcou()):
        zzxc = wea(i)
        for k in range(108):
            dt[o][0] = zzxc[0][0]
            #print(f"{i}  {k}")
            if(zzxc[k+1][1] != zzxc[k+1][1]):
                continue
            for j in range(19):
                dt[o][j+1] = zzxc[k+1][j]
            o += 1
    #print(o)
    return dt

In [23]:
def main():
    zzxc = [[[np.nan for x in range(2)] for y in range(2)] for z in range(2)]
    col = ["ID"]
    col = col + hea()
    zzxc[1] = pd.DataFrame(datae(), columns = col)
    zzxc[0] = pd.DataFrame(nam(), columns=["ID","Name","NameEN","Attribute"])
    return zzxc

In [24]:
r=main()
r[0]

        ID Name         NameEN Attribute
0   466880   板橋        BANQIAO   署屬有人氣象站
1   466900   淡水         TAMSUI   署屬有人氣象站
2   466910   鞍部           ANBU   署屬有人氣象站
3   466920   臺北         TAIPEI   署屬有人氣象站
4   466930  竹子湖        ZHUZIHU   署屬有人氣象站
5   466940   基隆        KEELUNG   署屬有人氣象站
6   466950  彭佳嶼      PENGJIAYU   署屬有人氣象站
7   466990   花蓮        HUALIEN   署屬有人氣象站
8   467050   新屋          XINWU   署屬有人氣象站
9   467060   蘇澳          SU-AO   署屬有人氣象站
10  467080   宜蘭          YILAN   署屬有人氣象站
11  467110   金門         KINMEN   署屬有人氣象站
12  467300  東吉島      DONGJIDAO   署屬有人氣象站
13  467350   澎湖         PENGHU   署屬有人氣象站
14  467410   臺南         TAINAN   署屬有人氣象站
15  467440   高雄      KAOHSIUNG   署屬有人氣象站
16  467480   嘉義         CHIAYI   署屬有人氣象站
17  467490   臺中       TAICHUNG   署屬有人氣象站
18  467530  阿里山        ALISHAN   署屬有人氣象站
19  467540   大武           DAWU   署屬有人氣象站
20  467550   玉山         YUSHAN   署屬有人氣象站
21  467571   新竹        HSINCHU   署屬有人氣象站
22  467590   恆春       HENGCHUN   署屬有人氣象站
23  467610   成功      CHENGGONG   署屬有人氣象站
24  467620   蘭嶼          LANYU   署屬有人氣象站
25  467650  日月潭  SUN MOON LAKE   署屬有人氣象站
26  467660   臺東        TAITUNG   署屬有人氣象站
27  467990   馬祖          MATSU   署屬有人氣象站
28  467270   田中      TianZhong   署屬有人氣象站
29  467441   高雄      Kaohsiung   署屬有人氣象站
30  466881   新北     New Taipei   署屬有人氣象站

In [25]:
r[1]

,ID,Year-Month,Mean AirTemperature (˚C),Maximum AirTemperature (˚C),MaximumDate AirTemperature,Minimum AirTemperature (˚C),MinimumDate AirTemperature,Accumulation Precipitation (mm),GE01Days Precipitation,Maximum WindSpeed (m s^-1),MaximumDate WindSpeed,Maximum WindDirection (˚),Maximum PeakGustSpeed (m s^-1),MaximumDate PeakGustSpeed,Maximum PeakGustDirection (˚),Mean RelativeHumidity (%),Minimum RelativeHumidity (%),MinimumDate RelativeHumidity,Mean AirPressure (hPa),Total SunshineDuration (hr)
0,466880,2015-01,16.3,24.5,2015-01-24,8.5,2015-01-24,24.7,8,7.0,2015-01-19,70.0,15.1,2015-01-19,80.0,67,36,2015-01-23,1020.7,80.4
1,466880,2015-02,17.0,26.8,2015-02-15,9.9,2015-02-09,95.5,11,6.5,2015-02-19,70.0,14.2,2015-02-19,50.0,72,32,2015-02-12,1018.7,66.3
2,466880,2015-03,18.7,30.7,2015-03-19,11.6,2015-03-11,187.2,13,6.0,2015-03-10,70.0,13.8,2015-03-24,40.0,77,43,2015-03-29,1017.4,78.9
3,466880,2015-04,22.6,33.9,2015-04-06,11.2,2015-04-15,79.4,10,6.8,2015-04-25,60.0,13.6,2015-04-25,60.0,74,21,2015-04-15,1013.0,134.2
4,466880,2015-05,26.0,35.5,2015-05-30,18.5,2015-05-05,239.4,15,7.2,2015-05-28,220.0,14.4,2015-05-28,190.0,76,43,2015-05-12,1007.8,106.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3056,466881,2023-08,28.3,36.9,2023-08-06,22.9,2023-08-17,372.5,17,10.4,2023-08-03,250.0,20.4,2023-08-04,270.0,81,46,2023-08-09,1001.2,185.7
3057,466881,2023-09,27.5,35.5,2023-09-24,20.0,2023-09-10,284.0,11,7.0,2023-09-04,90.0,18.4,2023-09-04,100.0,80,43,2023-09-16,1006.0,201.5
3058,466881,2023-10,24.2,33.0,2023-10-01,19.5,2023-10-26,202.5,15,6.5,2023-10-05,70.0,14.4,2023-10-05,50.0,83,49,2023-10-16,1012.2,78.8
3059,466881,2023-11,21.2,32.4,2023-11-06,11.1,2023-11-18,70.5,8,5.8,2023-11-28,100.0,12.6,2023-11-28,60.0,78,37,2023-11-04,1016.6,139.7
3060,466881,2023-12,17.9,30.0,2023-12-11,8.2,2023-12-22,135.0,13,5.6,2023-12-07,80.0,12.4,2023-12-16,60.0,85,45,2023-12-09,1019.0,81.5

In [26]:
# r[0].to_csv("weather_stations.csv", index = False)

In [27]:
r[1].to_csv("weatherInfoODS.csv", index = False)

In [28]:
r[1]['ID']=r[1]['ID'].astype('str')
r[1]['Minimum AirTemperature (˚C)'] = r[1]['Minimum AirTemperature (˚C)'].astype('str')
r[1]['Maximum AirTemperature (˚C)'] = r[1]['Maximum AirTemperature (˚C)'].astype('str')
r[1]['Mean AirTemperature (˚C)'] = r[1]['Mean AirTemperature (˚C)'].astype('str')
r[1]['Total SunshineDuration (hr)'] = r[1]['Total SunshineDuration (hr)'].astype('str')

In [29]:
data = r[1][['ID','Year-Month','Minimum AirTemperature (˚C)','Maximum AirTemperature (˚C)','Mean AirTemperature (˚C)','Accumulation Precipitation (mm)','Minimum RelativeHumidity (%)','Total SunshineDuration (hr)']]

years=[]
months=[]
for year, month in data['Year-Month'].str.split("-"):
    years.append(year)
    months.append(month)

data['year']=years
data['month']=months
data

C:\Users\T14 Gen 3\AppData\Local\Temp\ipykernel_20812\3632240383.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['year']=years
C:\Users\T14 Gen 3\AppData\Local\Temp\ipykernel_20812\3632240383.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['month']=months

,ID,Year-Month,Minimum AirTemperature (˚C),Maximum AirTemperature (˚C),Mean AirTemperature (˚C),Accumulation Precipitation (mm),Minimum RelativeHumidity (%),Total SunshineDuration (hr),year,month
0,466880,2015-01,8.5,24.5,16.3,24.7,36,80.4,2015,01
1,466880,2015-02,9.9,26.8,17.0,95.5,32,66.3,2015,02
2,466880,2015-03,11.6,30.7,18.7,187.2,43,78.9,2015,03
3,466880,2015-04,11.2,33.9,22.6,79.4,21,134.2,2015,04
4,466880,2015-05,18.5,35.5,26.0,239.4,43,106.2,2015,05
...,...,...,...,...,...,...,...,...,...,...
3056,466881,2023-08,22.9,36.9,28.3,372.5,46,185.7,2023,08
3057,466881,2023-09,20.0,35.5,27.5,284.0,43,201.5,2023,09
3058,466881,2023-10,19.5,33.0,24.2,202.5,49,78.8,2023,10
3059,466881,2023-11,11.1,32.4,21.2,70.5,37,139.7,2023,11
3060,466881,2023-12,8.2,30.0,17.9,135.0,45,81.5,2023,12

In [30]:
for col in  ['Minimum AirTemperature (˚C)','Maximum AirTemperature (˚C)', 'Mean AirTemperature (˚C)',
       'Accumulation Precipitation (mm)', 'Minimum RelativeHumidity (%)',
       'Total SunshineDuration (hr)', 'year', 'month']:
       data[col] = pd.to_numeric(data[col], errors='coerce').replace([np.nan],[None])
data

C:\Users\T14 Gen 3\AppData\Local\Temp\ipykernel_20812\1794898402.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = pd.to_numeric(data[col], errors='coerce').replace([np.nan],[None])

,ID,Year-Month,Minimum AirTemperature (˚C),Maximum AirTemperature (˚C),Mean AirTemperature (˚C),Accumulation Precipitation (mm),Minimum RelativeHumidity (%),Total SunshineDuration (hr),year,month
0,466880,2015-01,8.5,24.5,16.3,24.7,36.0,80.4,2015,1
1,466880,2015-02,9.9,26.8,17.0,95.5,32.0,66.3,2015,2
2,466880,2015-03,11.6,30.7,18.7,187.2,43.0,78.9,2015,3
3,466880,2015-04,11.2,33.9,22.6,79.4,21.0,134.2,2015,4
4,466880,2015-05,18.5,35.5,26.0,239.4,43.0,106.2,2015,5
...,...,...,...,...,...,...,...,...,...,...
3056,466881,2023-08,22.9,36.9,28.3,372.5,46.0,185.7,2023,8
3057,466881,2023-09,20.0,35.5,27.5,284.0,43.0,201.5,2023,9
3058,466881,2023-10,19.5,33.0,24.2,202.5,49.0,78.8,2023,10
3059,466881,2023-11,11.1,32.4,21.2,70.5,37.0,139.7,2023,11
3060,466881,2023-12,8.2,30.0,17.9,135.0,45.0,81.5,2023,12

In [31]:

data.to_csv("weatherInfoDW.csv", index = False)